spelling=Rastniv\u00EEs
cap=Vegurandina herfa girdek
par=Kevanek
wordpart=Word parts of compounds
comma=Bikaran\u00EEna xalb\u00EAhnok\u00EA
proofreading=Proofreading
style=Style checking
compound=Bin\u00EA peyv\u00EAn hevdudan\u00EE y\u00EAn \u015Fa\u015F x\u00EAz bike
allcompound=Bin\u00EA hem\u00FB peyv\u00EAn hevdudan\u00EE y\u00EAn p\u00EAkhat\u00EE x\u00EAz bike
grammar=Possible mistakes
money=Consistency of money amounts
duplication=Word duplication
dup0=Word duplication
dup=Duplication within clauses
dup2=Duplication within sentences
dup3=Allow previous checkings with affixes
numpart=Thousand separation of numbers
typography=Tipografya
quot=Quotation marks
apost=Dabir
dash=Bendik
elli=S\u00EAxal
ligature=Ligature suggestion
noligature=Underline ligatures
frac=Parhijmar
thin=Thin space
spaces=Double spaces
spaces2=More spaces
idx=Indices
minus=K\u00EAmek
SI=P\u00EEvan
hyphen=K\u00EEtekirina peyv\u00EAn nekiv\u015F
